apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lakehouse-track

resources:
  - namespace.yaml
  - secret.yaml
  # ConfigMaps
  - configmap-nginx.yaml
  - configmap-vector.yaml
  - configmap-supervisor.yaml
  - configmap-meta-sync.yaml
  # Workloads
  - collection-deployment.yaml
  - hpa-collection.yaml
  - meta-api-deployment.yaml
  - postgres-statefulset.yaml
  - minio-statefulset.yaml
  - starrocks-fe.yaml
  - starrocks-cn.yaml
  # Services
  - services.yaml

commonLabels:
  app.kubernetes.io/part-of: lakehouse-track
  app.kubernetes.io/managed-by: kustomize
