apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paimon-lab
resources:
  - namespace.yaml
  - secret-postgres.yaml
  - secret-minio.yaml
  - configmap-vector.yaml
  - postgres.yaml
  - minio.yaml
  - nginx-vector.yaml
  - flink.yaml
  - starrocks.yaml
  - job-init-minio.yaml
